### ISSUE TITLE
Noob question - ModuleNotFoundError: No module named 'quilt3'

### ISSUE THREAD

**Issue by LPUoO** [AllenCell/quilt-data-access-tutorials#1]
Hi @jxchen01,

Is the Colab notebook meant to work as it is?
I am getting:
![image](https://user-images.githubusercontent.com/64419544/102929077-ce7a4b80-4491-11eb-89fd-d7718badf56b.png)
or:
![image](https://user-images.githubusercontent.com/64419544/102929140-f5388200-4491-11eb-8af7-d4069f2f5960.png)
from Jupyter

Thanks a lot

**Comment by jxchen01** [comment]
If you are using google colab to test out the demos, you need to install the required packages first. For example, `!pip install quilt3`. 

Later, I will try to update the demo to automatically detect if you are using goolge colab and install the requirement automatically.

**Comment by LPUoO** [comment]
Thank you very much,
I look forward to seeing the updated version with the installation of the requirements automatically,
 👍

**Comment by jxchen01** [comment]
update completed in PR (#2)
